version: '3.7'
services:
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'
  backend:
    build: backend
    ports:
      - '5000:5000'
    environment:
      - BUILD_MODE=development
